-- 003_seed.sql — starter content so the app launches non-empty.
-- Generated deterministically by DevAgent; idempotent (on conflict do nothing).

-- FaqEntries (faq_entries)
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('09bfb5f3-40c8-58fa-88c0-0763f014deab', 'How is this different from other coaching or habit apps?', 'Most apps reset to zero context every session. Executive Coach AI builds a persistent behavioral model of you over months — tracking your task completion patterns, emotional triggers, and avoidance cycles. The longer you use it, the sharper and more personalized your weekly retrospectives and nudges become.', 'Getting Started', 1, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('e9e0784a-3a00-5f74-84d3-9b6a2a0b1369', 'Is this designed for people with ADHD?', 'Yes. It''s built specifically for high-earning professionals with ADHD who struggle with consistency, drift, and avoidance cycles. Real-time nudges catch you when the system detects you''re slipping, and retrospectives are generated from your actual behavioral history — not generic advice.', 'Getting Started', 2, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('d320225d-4a90-5fee-8c76-7ff45e7fe6f5', 'What is a weekly retrospective?', 'Every week, the app generates a structured review drawn directly from your own behavior that week — what you completed, where you avoided, and which emotional triggers preceded drift. It surfaces patterns you can''t see day-to-day and suggests one or two concrete adjustments for the week ahead.', 'Features', 3, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('952b9cb7-9155-59e9-8594-5ea61cb7c782', 'How do real-time nudges work?', 'The app continuously monitors your activity against your established patterns. When it detects early signs of drift — like repeatedly deferring a high-priority task or a shift in your usual rhythm — it sends a timely, context-aware nudge to help you re-engage before the avoidance cycle takes hold.', 'Features', 4, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('89fee4e4-1777-5255-83b8-f1ed55216b1f', 'How is my behavioral data protected?', 'Your behavioral history is private to your account and used only to power your coaching. We never sell your data or share it with advertisers. You can export or permanently delete your full history at any time from settings.', 'Privacy & Data', 5, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('a0125c90-e72f-5454-8b02-8b4eabaa83d9', 'How much does it cost?', 'Executive Coach AI is built for the $60K+ professional who can''t justify a $300/hour human coach but needs more than a free to-do app. Pricing is a flat monthly subscription with a free trial so you can experience how coaching quality compounds before committing.', 'Billing', 6, true) on conflict (id) do nothing;
