-- 003_seed.sql — starter content so the app launches non-empty.
-- Generated deterministically by DevAgent; idempotent (on conflict do nothing).

-- FaqEntries (faq_entries)
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('09bfb5f3-40c8-58fa-88c0-0763f014deab', 'How is this different from a habit tracker or generic coaching app?', 'Most apps reset to zero context every session — you re-explain yourself each time. Executive Coach AI builds a persistent behavioral model of you over months, tracking task completion patterns, emotional triggers, and avoidance cycles. Your weekly retrospectives are generated from your actual history, so the coaching quality compounds the longer you stay.', 'Getting Started', 1, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('e9e0784a-3a00-5f74-84d3-9b6a2a0b1369', 'Is this designed for people with ADHD?', 'Yes. It''s built specifically for professionals with ADHD who struggle with avoidance cycles, follow-through, and emotional drift. Real-time nudges fire when the system detects you slipping off-pattern, and retrospectives surface the triggers behind your avoidance rather than just scolding you for missed tasks.', 'Getting Started', 2, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('d320225d-4a90-5fee-8c76-7ff45e7fe6f5', 'What happens in a weekly retrospective?', 'Each week the app analyzes your task completion data, logged emotional triggers, and detected avoidance patterns, then generates a structured review of what worked, where you drifted, and one or two concrete adjustments for the week ahead. It''s grounded entirely in your own behavioral history, not generic advice.', 'Features', 3, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('952b9cb7-9155-59e9-8594-5ea61cb7c782', 'How do real-time nudges work?', 'The app continuously watches for drift — a stalled high-priority task, a recurring avoidance window, or a trigger you''ve flagged before. When it detects you heading into a known pattern, it sends a timely, specific nudge instead of a generic reminder, so you can course-correct before the cycle takes hold.', 'Features', 4, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('89fee4e4-1777-5255-83b8-f1ed55216b1f', 'Is my behavioral data private?', 'Your behavioral model is yours. Data is encrypted, never sold, and used only to power your coaching. You can export or permanently delete your full history at any time from settings.', 'Privacy & Data', 5, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('a0125c90-e72f-5454-8b02-8b4eabaa83d9', 'How much does it cost?', 'Executive Coach AI is built for the $60K+ professional who needs serious coaching without the price of a private executive coach. It runs on a monthly subscription with a free trial period so you can experience how the coaching compounds before committing.', 'Billing', 6, true) on conflict (id) do nothing;
