-- 003_seed.sql — starter content so the app launches non-empty.
-- Generated deterministically by DevAgent; idempotent (on conflict do nothing).

-- FaqEntries (faq_entries)
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('09bfb5f3-40c8-58fa-88c0-0763f014deab', 'How is this different from other coaching or habit apps?', 'Most apps reset to zero context every session. Executive Coach AI builds a persistent behavioral model of you over weeks and months — tracking your task completion patterns, emotional triggers, and avoidance cycles. Your weekly retrospectives are generated from your own real history, so coaching quality compounds the longer you stay.', 'Getting Started', 1, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('e9e0784a-3a00-5f74-84d3-9b6a2a0b1369', 'Is this designed for people with ADHD?', 'Yes. It''s built for high-earning professionals who struggle with avoidance cycles, follow-through, and emotional drift. Instead of generic reminders, it detects when you''re drifting in real time and delivers a structured nudge based on your specific patterns — not a one-size-fits-all checklist.', 'Getting Started', 2, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('d320225d-4a90-5fee-8c76-7ff45e7fe6f5', 'What is a weekly retrospective and how does it work?', 'Each week the app analyzes your logged tasks, completion rates, and emotional check-ins to produce a structured review of what worked, where you stalled, and which triggers preceded avoidance. It surfaces concrete patterns and a small set of focus adjustments for the coming week, rather than vague encouragement.', 'Features', 3, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('952b9cb7-9155-59e9-8594-5ea61cb7c782', 'How does the real-time drift detection work?', 'The model watches for signals it has learned predict avoidance for you — like repeatedly rescheduling a task, long idle gaps, or negative emotional check-ins clustering around a project. When it spots drift early, it sends a short, targeted nudge so you can course-correct before the whole day slips.', 'Features', 4, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('89fee4e4-1777-5255-83b8-f1ed55216b1f', 'How is my behavioral data kept private?', 'Your behavioral history is yours. Data is encrypted in transit and at rest, never sold, and never used to train models shared with other users. You can export or permanently delete your full history at any time from settings.', 'Privacy & Data', 5, true) on conflict (id) do nothing;
insert into public.faq_entries (id, question, answer, category, sort_order, is_active) values ('a0125c90-e72f-5454-8b02-8b4eabaa83d9', 'How long before the coaching feels accurate?', 'You''ll get useful structure in week one, but the model needs roughly two to four weeks of consistent check-ins to learn your specific triggers and rhythms. The value grows over time — by month three the retrospectives reflect deep, personalized patterns you likely wouldn''t notice yourself.', 'Getting Started', 6, true) on conflict (id) do nothing;
